Processing data in models
amentetteh/ror-blog-app pull request #2
Opened 2023-03-04 18:29 UTC by amentetteh

In this PR, below guidelines have been followed:

### Project requirements

### Create models
-  Create model classes for all entities as shown in the [ERD diagram](../images/blog_app_erd_v1_1.png).
-  Set up associations between models.
    - Remember that `author_id` column in `posts` table should be the foreign_key for the `users` table.

### Use models to insert data
- Familiarize yourself with ['rails c' command](https://guides.rubyonrails.org/command_line.html#bin-rails-console).
- Open rails console for your project.
- Create at least one user by running the following code:
    ```ruby
       first_user = User.create(name: 'Tom', photo: 'https://unsplash.com/photos/F_-0BxGuVvo', bio: 'Teacher from Mexico.')
       second_user = User.create(name: 'Lilly', photo: 'https://unsplash.com/photos/F_-0BxGuVvo', bio: 'Teacher from Poland.')
    ```
- Create at least 4 posts written by one of the users you created by running the following code:
    ```ruby
       first_post = Post.create(author: first_user, title: 'Hello', text: 'This is my first post')
    ```
- Create at least 6 posts comments for one of the posts you created by running the following code:
    ```ruby
       Comment.create(post: first_post, author: second_user, text: 'Hi Tom!' )
    ```
- Use other [CRUD methods](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/lessons/active_record_crud.md) to find, update and delete entities.

### Create custom methods
Your models should include some additional methods.
-  Users
    - A method that returns the 3 most recent posts for a given user.
-  Posts
    - A method that updates the posts counter for a user.
    - A method which returns the 5 most recent comments for a given post.
-  Comments
    - A method that updates the comments counter for a post.
-  Likes
    - A method that updates the likes counter for a post.
- Go to `rails c` and check if your methods are working.

2023-03-04 18:53 UTC, Deepakdanger requested changes
Hi @amentetteh , 

Good job so far! 👏
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight :100: 
- No linter error :heavy_check_mark: 
- Website looks professional :+1: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-04 18:53 UTC, Deepakdanger commented on app/models/comment.rb
> +  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
- [ ] Here `foreign_key` is not necessary, Kindly remove them.
ex-
```ruby
belongs_to :author, class_name: 'User'
```

2023-03-04 18:53 UTC, Deepakdanger commented on app/models/comment.rb
> +  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'
- [ ] Here `class_name & foreign_key` not require .rails can easily understand the table `Post. So kindly remove them.ex-
```
belongs_to :post
```

2023-03-04 18:53 UTC, Deepakdanger commented on app/models/like.rb
> +  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
- [ ] Here `foreign_key` is not necessary, Kindly remove them

2023-03-04 18:53 UTC, Deepakdanger commented on app/models/like.rb
> +  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'
- [ ] Here `class_name & foreign_key` not require .rails can easily understand the table `Post. So kindly remove them.

2023-03-04 18:53 UTC, Deepakdanger commented on app/models/post.rb
> +  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
- [ ]  Here `foreign_key` is not necessary, Kindly remove them
ex-
```
belongs_to :author, class_name: 'User'
```

2023-03-04 18:53 UTC, Deepakdanger commented on app/models/post.rb
> +  has_many :likes, class_name: 'Like', foreign_key: 'post_id'
- [ ] Here `class_name & foreign_key` not require .rails can easily understand the table `Like & Comment` Table. So kindly remove them.ex-

```ruby
has_many :comments
has_many :likes
```

2023-03-04 18:53 UTC, Deepakdanger commented on app/models/user.rb
> +  has_many :posts, class_name: 'Post', foreign_key: 'author_id'
- [ ] Here `class_name` is not necessary, Kindly remove them. 
- Rails can easily understand the `Comment, Like & Post` table., But to recognize `User` we have implemented `author_id` as a foreign key in all tables `comment, like & post` so we need a foreign key only here.ex-
```
has_many :posts, foreign_key: 'author_id'
has_many :comments, foreign_key: 'author_id'
has_many :likes, foreign_key: 'author_id'
```

2023-03-04 18:53 UTC, Deepakdanger commented on app/models/post.rb
> +  end
- [ ] Move this method above `private` Line -8. Because we can call it from another place like `controller or views` otherwise calling this method will give error `Cannot call the private method `

2023-03-04 19:41 UTC, MeqdamAlqudah approved these changes
Hi @amentetteh , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![image](https://user-images.githubusercontent.com/74744787/222925247-49eb65f2-3a8a-46d6-8d88-ee246ded3af7.png)

## Highlights 
:+1: no linter errors 
:+1: associations are setup correctly 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-05 01:23 UTC, merged

2023-05-05 16:49 UTC, omarsalem7 commented
Hi @amentetteh 😊, 
# STATUS: APPROVED! 🥇 💯 

<!--- ![giphy](https://media.giphy.com/media/n5VaQoW39Z9S0/giphy.gif) -->

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
✅ Project has met all the technical aspects you needed for this project. Keep rocking! 

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-12 15:51 UTC, DammyShittu reviewed
Hi @amentetteh,

## APPROVED 🟢

## Highlights
✔️ Project met all technical requirements

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._