Implement integrations specs and fix n+1 problems
amentetteh/ror-blog-app pull request #8
Opened 2023-03-22 11:00 UTC by amentetteh

In this PR, we followed below requirements:

- Solve the N+1 problem when fetching all posts and their comments for a user. Screenshots of the results are as follows: 
![003](https://user-images.githubusercontent.com/11460090/226883402-c821713a-ddc6-4c5f-ac90-350ad3be9159.png)
![002](https://user-images.githubusercontent.com/11460090/226883415-474c7e9c-efb8-4a6a-af38-b9904318298d.png)
![01](https://user-images.githubusercontent.com/11460090/226883418-9695c660-aa8c-453c-b94d-95a3470147fe.png)

- Use Capybara to write integration tests for each view in our project, which includes user index page, user show page, post index page, and post show page

2023-03-22 11:15 UTC, DammyShittu commented
Hi @amentetteh @sebalp100 and @SimonGideon,

While you made a great effort in this project, I cannot proceed to review your code.

## Invalid Code Review Request

### You have submitted a project that has failed linter checks

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-22 11:38 UTC, DammyShittu requested changes
Hi @amentetteh, @sebalp100 and @SimonGideon,

## Highlights
✔️ Capybara for tests

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-22 11:38 UTC, DammyShittu commented on spec/integration/posts_spec.rb
> +  end
- **[OPTIONAL]** We want to organize the tests. Kindly move this post show tests to their own file. We are testing 4 different views, so it makes sense that we should have 4 different corresponding test files.

2023-03-22 11:38 UTC, DammyShittu commented on spec/integration/users_spec.rb
> +  end
- **[OPTIONAL]** Kindly move these tests to their own file.

2023-03-22 11:38 UTC, DammyShittu commented on spec/integration/users_spec.rb
> +  end
- [ ] For the user show page, kindly add:

  - Test that redirects to the post's show page when you click on a user's post.

2023-03-22 11:38 UTC, DammyShittu commented on spec/integration/posts_spec.rb
> +  end
- [ ] For the post index page, kindly add:

  - Test that asserts you can see a post's title.

2023-03-22 11:38 UTC, DammyShittu commented on spec/integration/posts_spec.rb
> +  end
- [ ] For the post show page, kindly add:

  - Test that asserts you can see who wrote the post.

2023-03-23 13:27 UTC, amentetteh commented on spec/integration/posts_spec.rb
> +  end
Thanks.

2023-03-23 16:10 UTC, DammyShittu approved these changes
Hi @amentetteh, @sebalp100 and @SimonGideon,

## APPROVED 🟢

## Highlights
✔️ Tests are well organized

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 16:27 UTC, merged